name: walletconnect_demo
version: 0.1.0
publish_to: 'none'

dependencies:
  convert: ^2.1.1
  dio: ^3.0.10
  walletconnect:
    path: ../
  ethereum_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-transaction-codec
      ref: main
  eth_abi_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-abi-codec
      ref: main
  sprintf: ^4.0.0
  test: any
